### ISSUE TITLE
lobby - clean up header

### ISSUE THREAD

**Issue by mbeckmanssf** [SoftStackFactory/PersonaTest-UI#138]
app title is squished with buttons for 'Personal' and 'Professional'

**Comment by brieverett** [comment]
![Ios header.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d2e6c4c66958001648443e/125516c66e82c728ace21e0d46c19b89638a86a88becad01e81fe086264c22703d46f96925dce02be81a2958560d4dfd145f5f44fefc802bf4e23876984019af80330b2b9b645bf9fa9015ad03ba2a8a4a85b0b58344c0e83925ee829d02.PNG)
