### ISSUE TITLE
results (mobile) - right side chart is cut off

### ISSUE THREAD

**Issue by jtranssf** [SoftStackFactory/PersonaTest-UI#143]
change the css or padding a little so that "intellect" isn't cut off on the right

**Comment by GCodeON** [comment]
![2017-10-14 04 49 11 pm](https://user-images.githubusercontent.com/19736673/31580330-19bae6b8-b101-11e7-9946-4fc4503edcb9.png)

**Comment by GCodeON** [comment]
I've tried to add padding and margins to the canvas object, and it works. However it has no effect on the medium mobile screen size(375x593).

**Comment by GCodeON** [comment]
#161 Here is the attempt at fixing this
